version: "3.8"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./db/migrations:/migrations
    command:
      [ "--verbose", "-database", "postgres://gostack:gostack_password@database:5432/gostack?sslmode=disable", "-path", "/migrations", "up" ]

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - migrate
    networks:
      - default
    ports:
      - "8080:8080"

volumes:
  data:

